name: backend_project
description: A Dart backend for a barbershop management app using SQLite
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  sqlite3: ^1.8.0
  path: ^1.8.0
